### ISSUE TITLE
Temperature compensation

### ISSUE THREAD

**Issue by Swiftnesses** [MikaPetteriLundgren/Arduino-Oil-Level-Logger#1]
Howdy, nice sketch. I'd suggest adding temperature compensation to your ultrasonic readings. Readings can vary up to 1cm with ambient day | night changes (I'm assuming your sensor doesn't apply a correction like the URM37, for example).

Some info is here:

http://www.instructables.com/id/Temperature-Compensated-Ultrasonic-Range-Finder-Wi/
https://www.davidpilling.com/wiki/index.php/HCSR04

Mark

**Comment by Swiftnesses** [comment]
Too much wine, re-read the code and noticed the correction. Doh!

**Comment by MikaPetteriLundgren** [comment]
No problem. That happens easily when drinking too much wine... ;-)
